import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full px-5 py-7 border bottom-1 shadow-sm fixed z-20 top-0 start-0 h-fit bg-white">
          <div className="items-center justify-between w-fit d-flex mx-auto">
            <Link
              href="/"
              className="text-white text-lg py-2 px-3 bg-blue-600 hover:bg-blue-800 rounded-lg"
            >
              Task 1
            </Link>
            <Link
              href="/Task2"
              className="text-white text-lg ml-10 py-2 px-3 bg-blue-600 hover:bg-blue-800 rounded-lg"
            >
              Task 2
            </Link>
            <Link
              href="/Task3"
              className="text-white text-lg ml-10 py-2 px-3 bg-blue-600 hover:bg-blue-800 rounded-lg"
            >
              Task 3
            </Link>
            <Link
              href="/Task4"
              className="text-white text-lg ml-10 py-2 px-3 bg-blue-600 hover:bg-blue-800 rounded-lg"
            >
              Task 4
            </Link>
            <Link
              href="/Task5"
              className="text-white text-lg ml-10 py-2 px-3 bg-blue-600 hover:bg-blue-800 rounded-lg"
            >
              Task 5
            </Link>
            <Link
              href="/Task6"
              className="text-white text-lg ml-10 py-2 px-3 bg-blue-600 hover:bg-blue-800 rounded-lg"
            >
              Task 6
            </Link>
          </div>
        </div>
        <div className="mt-16">{children}</div>
      </body>
    </html>
  );
}
